pose_mapping = {
    "def": "print(\" Not enabled \")",
    "and": " and ",
    "bracket": "( ",
    "not bracket": ") ",
    "colon": ": ",
    "divide": " / ",
    "else": "else",
    "enter": "\n",
    "not enter": "Backspace",
    "equals": " = ",
    "greater_than": " > ",
    "hello_world": "Hello world!",
    "if": "if",
    "less_than": " < ",
    "minus": " - ",
    "mult": " * ",
    "not": "!",
    "one": "1",
    "or": " or ",
    "plus": " + ",
    "print": "print",
    "tab": "\t",
    "two": "2",
    "up": "Up",
    "not up": "Down",
    "while": "while"
}